spring:
  jpa:
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/library
          jwk-set-uri: http://localhost:8083/realms/library/protocol/openid-connect/certs
